# Generated by Django 6.1 on 2026-08-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('base_hp', models.IntegerField(default=2500)),
                ('base_attack', models.IntegerField(default=115)),
            ],
        ),
    ]
