# Generated by Django 6.1 on 2026-09-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='base_attack',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='hero',
            name='base_hp',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='hero',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
